//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unvell.JustCapture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unvell.JustCapture.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture and edit a region of the screen.
        /// </summary>
        public static string action_capture_and_edit_free_region {
            get {
                return ResourceManager.GetString("action_capture_and_edit_free_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture and save a region of the screen.
        /// </summary>
        public static string action_capture_and_save_free_region {
            get {
                return ResourceManager.GetString("action_capture_and_save_free_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture full screen into clipboard.
        /// </summary>
        public static string action_capture_full_screen_into_clipboard {
            get {
                return ResourceManager.GetString("action_capture_full_screen_into_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a region of the screen.
        /// </summary>
        public static string action_free_region {
            get {
                return ResourceManager.GetString("action_free_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Editor.
        /// </summary>
        public static string action_image_editor {
            get {
                return ResourceManager.GetString("action_image_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail last captured picture.
        /// </summary>
        public static string action_mail_last_captured_picture {
            get {
                return ResourceManager.GetString("action_mail_last_captured_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save last captured picture.
        /// </summary>
        public static string action_save_last_captured_picture {
            get {
                return ResourceManager.GetString("action_save_last_captured_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a foreground window of the screen.
        /// </summary>
        public static string action_select_window {
            get {
                return ResourceManager.GetString("action_select_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files.
        /// </summary>
        public static string all_supported_files {
            get {
                return ResourceManager.GetString("all_supported_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already running under windows system tray..
        /// </summary>
        public static string already_running {
            get {
                return ResourceManager.GetString("already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        public static string arrow {
            get {
                return ResourceManager.GetString("arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string bold {
            get {
                return ResourceManager.GetString("bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        public static string btn_about {
            get {
                return ResourceManager.GetString("btn_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Number.
        /// </summary>
        public static string btn_add_number {
            get {
                return ResourceManager.GetString("btn_add_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Text.
        /// </summary>
        public static string btn_add_text {
            get {
                return ResourceManager.GetString("btn_add_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Snapshot.
        /// </summary>
        public static string btn_capture {
            get {
                return ResourceManager.GetString("btn_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture current full screen.
        /// </summary>
        public static string btn_capture_current_full_screen {
            get {
                return ResourceManager.GetString("btn_capture_current_full_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a &amp;region of the screen.
        /// </summary>
        public static string btn_capture_free_region {
            get {
                return ResourceManager.GetString("btn_capture_free_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string btn_capture_to_clipboard {
            get {
                return ResourceManager.GetString("btn_capture_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a foreground &amp;window.
        /// </summary>
        public static string btn_capture_window {
            get {
                return ResourceManager.GetString("btn_capture_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Check for update.
        /// </summary>
        public static string btn_check_for_updates {
            get {
                return ResourceManager.GetString("btn_check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected image.
        /// </summary>
        public static string btn_clip_image {
            get {
                return ResourceManager.GetString("btn_clip_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string btn_close {
            get {
                return ResourceManager.GetString("btn_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string btn_copy {
            get {
                return ResourceManager.GetString("btn_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ut.
        /// </summary>
        public static string btn_cut {
            get {
                return ResourceManager.GetString("btn_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Deselect.
        /// </summary>
        public static string btn_deselect {
            get {
                return ResourceManager.GetString("btn_deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Don&apos;t show this message again.
        /// </summary>
        public static string btn_do_not_show_again {
            get {
                return ResourceManager.GetString("btn_do_not_show_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw &amp;Arrow.
        /// </summary>
        public static string btn_draw_arrow {
            get {
                return ResourceManager.GetString("btn_draw_arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw &amp;Ellipse.
        /// </summary>
        public static string btn_draw_ellipse {
            get {
                return ResourceManager.GetString("btn_draw_ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw &amp;Line.
        /// </summary>
        public static string btn_draw_line {
            get {
                return ResourceManager.GetString("btn_draw_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw &amp;Rectangle.
        /// </summary>
        public static string btn_draw_rectangle {
            get {
                return ResourceManager.GetString("btn_draw_rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string btn_edit {
            get {
                return ResourceManager.GetString("btn_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on every startup(Recommend).
        /// </summary>
        public static string btn_enable_check_for_updates {
            get {
                return ResourceManager.GetString("btn_enable_check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string btn_exit {
            get {
                return ResourceManager.GetString("btn_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string btn_file {
            get {
                return ResourceManager.GetString("btn_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Full Screen.
        /// </summary>
        public static string btn_full_screen {
            get {
                return ResourceManager.GetString("btn_full_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string btn_help {
            get {
                return ResourceManager.GetString("btn_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Homepage....
        /// </summary>
        public static string btn_homepage {
            get {
                return ResourceManager.GetString("btn_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Image.
        /// </summary>
        public static string btn_image {
            get {
                return ResourceManager.GetString("btn_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image &amp;Editor....
        /// </summary>
        public static string btn_image_editor {
            get {
                return ResourceManager.GetString("btn_image_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Inner line:.
        /// </summary>
        public static string btn_inner_line {
            get {
                return ResourceManager.GetString("btn_inner_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language:.
        /// </summary>
        public static string btn_language {
            get {
                return ResourceManager.GetString("btn_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Aspect &amp;Ratio.
        /// </summary>
        public static string btn_lock_aspect_ratio {
            get {
                return ResourceManager.GetString("btn_lock_aspect_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string btn_more {
            get {
                return ResourceManager.GetString("btn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string btn_new {
            get {
                return ResourceManager.GetString("btn_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        public static string btn_next {
            get {
                return ResourceManager.GetString("btn_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        public static string btn_open {
            get {
                return ResourceManager.GetString("btn_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Outer line:.
        /// </summary>
        public static string btn_outer_line {
            get {
                return ResourceManager.GetString("btn_outer_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string btn_paste {
            get {
                return ResourceManager.GetString("btn_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        public static string btn_print {
            get {
                return ResourceManager.GetString("btn_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print last captured picture.
        /// </summary>
        public static string btn_print_last_picture {
            get {
                return ResourceManager.GetString("btn_print_last_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        public static string btn_redo {
            get {
                return ResourceManager.GetString("btn_redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Number(&amp;W).
        /// </summary>
        public static string btn_reset_number {
            get {
                return ResourceManager.GetString("btn_reset_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        public static string btn_reset_region {
            get {
                return ResourceManager.GetString("btn_reset_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resize Image....
        /// </summary>
        public static string btn_resize_image {
            get {
                return ResourceManager.GetString("btn_resize_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember last captured region.
        /// </summary>
        public static string btn_restore_last_region {
            get {
                return ResourceManager.GetString("btn_restore_last_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Run JustCapture automatically when Windows starts.
        /// </summary>
        public static string btn_run_on_windows_starts {
            get {
                return ResourceManager.GetString("btn_run_on_windows_starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string btn_save_as {
            get {
                return ResourceManager.GetString("btn_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save last captured picture....
        /// </summary>
        public static string btn_save_last_picture {
            get {
                return ResourceManager.GetString("btn_save_last_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale....
        /// </summary>
        public static string btn_scale {
            get {
                return ResourceManager.GetString("btn_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select.
        /// </summary>
        public static string btn_select {
            get {
                return ResourceManager.GetString("btn_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        public static string btn_select_all {
            get {
                return ResourceManager.GetString("btn_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;Window.
        /// </summary>
        public static string btn_select_window {
            get {
                return ResourceManager.GetString("btn_select_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings....
        /// </summary>
        public static string btn_settings {
            get {
                return ResourceManager.GetString("btn_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Shadow.
        /// </summary>
        public static string btn_shadow {
            get {
                return ResourceManager.GetString("btn_shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Toolbar.
        /// </summary>
        public static string btn_show_toolbar {
            get {
                return ResourceManager.GetString("btn_show_toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;toolbox in capture tool.
        /// </summary>
        public static string btn_show_toolbar_in_capture_tool {
            get {
                return ResourceManager.GetString("btn_show_toolbar_in_capture_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Skip.
        /// </summary>
        public static string btn_skip {
            get {
                return ResourceManager.GetString("btn_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips....
        /// </summary>
        public static string btn_start_tips {
            get {
                return ResourceManager.GetString("btn_start_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Status Bar.
        /// </summary>
        public static string btn_status_Bar {
            get {
                return ResourceManager.GetString("btn_status_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Thumb:.
        /// </summary>
        public static string btn_thumb {
            get {
                return ResourceManager.GetString("btn_thumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toolbar.
        /// </summary>
        public static string btn_toolbar {
            get {
                return ResourceManager.GetString("btn_toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        public static string btn_tools {
            get {
                return ResourceManager.GetString("btn_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        public static string btn_undo {
            get {
                return ResourceManager.GetString("btn_undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        public static string btn_view {
            get {
                return ResourceManager.GetString("btn_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string capture {
            get {
                return ResourceManager.GetString("capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a region of the screen.
        /// </summary>
        public static string capture_free_region {
            get {
                return ResourceManager.GetString("capture_free_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture current full screen.
        /// </summary>
        public static string capture_full_screen {
            get {
                return ResourceManager.GetString("capture_full_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Tool.
        /// </summary>
        public static string capture_tool {
            get {
                return ResourceManager.GetString("capture_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured Image.
        /// </summary>
        public static string captured_image {
            get {
                return ResourceManager.GetString("captured_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string check_for_updates {
            get {
                return ResourceManager.GetString("check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;coordinate information.
        /// </summary>
        public static string chk_show_coordinate_info {
            get {
                return ResourceManager.GetString("chk_show_coordinate_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Text.
        /// </summary>
        public static string edit_text {
            get {
                return ResourceManager.GetString("edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string full_screen {
            get {
                return ResourceManager.GetString("full_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        public static string generic {
            get {
                return ResourceManager.GetString("generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check following actions to activate it and you can set different shortcut keys for every actions..
        /// </summary>
        public static string hotkeys_custom_tip {
            get {
                return ResourceManager.GetString("hotkeys_custom_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Editor.
        /// </summary>
        public static string image_editor {
            get {
                return ResourceManager.GetString("image_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image could not be opened successfully. The file may be in the incorrect format..
        /// </summary>
        public static string incorrect_format {
            get {
                return ResourceManager.GetString("incorrect_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string italic {
            get {
                return ResourceManager.GetString("italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Height:.
        /// </summary>
        public static string lab_height {
            get {
                return ResourceManager.GetString("lab_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier Scale:.
        /// </summary>
        public static string lab_magnifier_scale {
            get {
                return ResourceManager.GetString("lab_magnifier_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string lab_no_magnifier_scale {
            get {
                return ResourceManager.GetString("lab_no_magnifier_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Operation:.
        /// </summary>
        public static string lab_start_operation {
            get {
                return ResourceManager.GetString("lab_start_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unit:.
        /// </summary>
        public static string lab_unit {
            get {
                return ResourceManager.GetString("lab_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Width:.
        /// </summary>
        public static string lab_width {
            get {
                return ResourceManager.GetString("lab_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Image.
        /// </summary>
        public static string new_image {
            get {
                return ResourceManager.GetString("new_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        public static string new_version_available {
            get {
                return ResourceManager.GetString("new_version_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Available!
        ///Click here to download the latest version..
        /// </summary>
        public static string new_version_notify {
            get {
                return ResourceManager.GetString("new_version_notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Color.
        /// </summary>
        public static string no_color {
            get {
                return ResourceManager.GetString("no_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already running the most recent version of {0}..
        /// </summary>
        public static string no_new_version {
            get {
                return ResourceManager.GetString("no_new_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No picture captured yet..
        /// </summary>
        public static string no_picture_captured {
            get {
                return ResourceManager.GetString("no_picture_captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough permission to add startup items, please run with administrator..
        /// </summary>
        public static string not_enough_permission {
            get {
                return ResourceManager.GetString("not_enough_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        public static string open_image {
            get {
                return ResourceManager.GetString("open_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel.
        /// </summary>
        public static string pixel {
            get {
                return ResourceManager.GetString("pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string rectangle {
            get {
                return ResourceManager.GetString("rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Selection.
        /// </summary>
        public static string region_selection {
            get {
                return ResourceManager.GetString("region_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Number.
        /// </summary>
        public static string reset_number {
            get {
                return ResourceManager.GetString("reset_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset_region {
            get {
                return ResourceManager.GetString("reset_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Image.
        /// </summary>
        public static string resize_image {
            get {
                return ResourceManager.GetString("resize_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 90° CCW.
        /// </summary>
        public static string rotate_90ccw {
            get {
                return ResourceManager.GetString("rotate_90ccw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 90° CW.
        /// </summary>
        public static string rotate_90cw {
            get {
                return ResourceManager.GetString("rotate_90cw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image as new file.
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to {0}?.
        /// </summary>
        public static string save_changes_confirm {
            get {
                return ResourceManager.GetString("save_changes_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        public static string save_image {
            get {
                return ResourceManager.GetString("save_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string scale {
            get {
                return ResourceManager.GetString("scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Image.
        /// </summary>
        public static string scale_image {
            get {
                return ResourceManager.GetString("scale_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Region.
        /// </summary>
        public static string select_region {
            get {
                return ResourceManager.GetString("select_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Window.
        /// </summary>
        public static string select_window {
            get {
                return ResourceManager.GetString("select_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Keys.
        /// </summary>
        public static string shortcut_keys {
            get {
                return ResourceManager.GetString("shortcut_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show shadow of shape.
        /// </summary>
        public static string show_shadow {
            get {
                return ResourceManager.GetString("show_shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string snapshot {
            get {
                return ResourceManager.GetString("snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Image Editor.
        /// </summary>
        public static string so_image_editor {
            get {
                return ResourceManager.GetString("so_image_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to capture a region.
        /// </summary>
        public static string so_start_capture {
            get {
                return ResourceManager.GetString("so_start_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in background (System Tray).
        /// </summary>
        public static string so_tray {
            get {
                return ResourceManager.GetString("so_tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Up.
        /// </summary>
        public static string start_up {
            get {
                return ResourceManager.GetString("start_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string strikethrough {
            get {
                return ResourceManager.GetString("strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make font larger.
        /// </summary>
        public static string text_larger {
            get {
                return ResourceManager.GetString("text_larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make font smaller.
        /// </summary>
        public static string text_smaller {
            get {
                return ResourceManager.GetString("text_smaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number will automatically increase. Press 0-9 digit key if you wish to change the current number..
        /// </summary>
        public static string tips_changenumber {
            get {
                return ResourceManager.GetString("tips_changenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press hotkeys anytime to get a snapshot of screen. The hotkeys can be customized in Settings dialog..
        /// </summary>
        public static string tips_hotkey {
            get {
                return ResourceManager.GetString("tips_hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also pick a foreground window to get the snapshot easily..
        /// </summary>
        public static string tips_select_window {
            get {
                return ResourceManager.GetString("tips_select_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to see an introduction about how to use JustCapture?.
        /// </summary>
        public static string tips_start_slides {
            get {
                return ResourceManager.GetString("tips_start_slides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JustCapture can be started up automatically when Windows starts and keeps running in background....
        /// </summary>
        public static string tips_tray {
            get {
                return ResourceManager.GetString("tips_tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string underline {
            get {
                return ResourceManager.GetString("underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        public static string untitled {
            get {
                return ResourceManager.GetString("untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
    }
}
